In [1]:
import pandas as pd
import numpy as np
from pathlib import Path

print("Libraries imported successfully!")

Libraries imported successfully!

In [4]:
file_path = Path("ApexPlanet_DataAnalytics_Dataset.xlsx")

df = pd.read_excel(
    file_path,
    sheet_name="Sales_Dataset"
)

print("Dataset loaded successfully!")
print("Number of rows:", df.shape[0])
print("Number of columns:", df.shape[1])

display(df.head())

Dataset loaded successfully!
Number of rows: 1000
Number of columns: 12

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90

In [5]:
# Display all column names
print("Column Names:")
print(df.columns.tolist())

# Check data types and non-null counts
print("\nDataset Information:")
df.info()

# View statistical summary
print("\nStatistical Summary:")
display(df.describe(include="all").T)

Column Names:
['Order_ID', 'Order_Date', 'Customer_ID', 'Customer_Name', 'Age', 'Gender', 'City', 'Product', 'Category', 'Quantity', 'Unit_Price', 'Total_Sales']

Dataset Information:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 12 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Order_ID       1000 non-null   object
 1   Order_Date     1000 non-null   object
 2   Customer_ID    1000 non-null   object
 3   Customer_Name  1000 non-null   object
 4   Age            980 non-null    float64
 5   Gender         1000 non-null   object
 6   City           987 non-null    object
 7   Product        1000 non-null   object
 8   Category       1000 non-null   object
 9   Quantity       1000 non-null   int64
 10  Unit_Price     1000 non-null   float64
 11  Total_Sales    1000 non-null   float64
dtypes: float64(3), int64(1), object(8)
memory usage: 93.9+ KB

Statistical Summary:

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Order_ID,1000,992,ORD100050,9,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Order_Date,1000,342,2025-04-16,10,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_ID,1000,947,CUST2515,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Customer_Name,1000,425,Customer_359,8,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Age,980.0,NaN,NaN,NaN,41.360204,13.822597,18.0,30.0,41.0,54.0,65.0
Gender,1000,2,Male,511,NaN,NaN,NaN,NaN,NaN,NaN,NaN
City,987,8,Patna,135,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Product,1000,6,Mobile,184,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Category,1000,5,Electronics,354,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Quantity,1000.0,NaN,NaN,NaN,5.435,2.838632,1.0,3.0,5.0,8.0,10.0
Unit_Price,1000.0,NaN,NaN,NaN,25486.78341,14179.402361,145.78,13895.7225,25398.74,37512.3825,49997.53
Total_Sales,1000.0,NaN,NaN,NaN,139399.43965,114100.051546,437.34,47066.6325,108594.025,203722.8825,493677.5

In [6]:
missing_values = df.isnull().sum()

print("Missing values in each column:")
display(missing_values.to_frame(name="Missing Count"))

print("Total missing cells:", df.isnull().sum().sum())

Missing values in each column:

               Missing Count
Order_ID                   0
Order_Date                 0
Customer_ID                0
Customer_Name              0
Age                       20
Gender                     0
City                      13
Product                    0
Category                   0
Quantity                   0
Unit_Price                 0
Total_Sales                0

Total missing cells: 33

In [7]:
# Exact duplicate rows
print("Exact duplicate rows:", df.duplicated().sum())

# Repeated order IDs
print(
    "Repeated Order_ID rows:",
    df["Order_ID"].duplicated().sum()
)

# Count unique order IDs
print("Unique Order_IDs:", df["Order_ID"].nunique())

Exact duplicate rows: 0
Repeated Order_ID rows: 8
Unique Order_IDs: 992

In [8]:
print("Order_Date data type:", df["Order_Date"].dtype)

print("Earliest order date:", df["Order_Date"].min())
print("Latest order date:", df["Order_Date"].max())

display(df["Order_Date"].head(10))

Order_Date data type: object
Earliest order date: 2025-01-01
Latest order date: 2026-01-01

0    2025-02-25
1    2025-10-14
2    2025-05-13
3    2025-12-02
4    2025-11-20
5    2025-12-31
6    2025-10-14
7    2025-12-05
8    2025-11-21
9    2025-04-16
Name: Order_Date, dtype: object

In [9]:
categorical_columns = [
    "Gender", "City", "Product", "Category"
]

for col in categorical_columns:
    print(f"\n--- {col} ---")
    print(df[col].value_counts(dropna=False))

--- Gender ---
Gender
Male      511
Female    489
Name: count, dtype: int64

--- City ---
City
Patna        135
Kolkata      133
Mumbai       131
Delhi        125
Hyderabad    125
Bengaluru    122
Gaya         117
Pune          99
NaN           13
Name: count, dtype: int64

--- Product ---
Product
Mobile    184
Book      178
Laptop    170
Chair     159
Shoes     156
Rice      153
Name: count, dtype: int64

--- Category ---
Category
Electronics    354
Education      178
Furniture      159
Fashion        156
Grocery        153
Name: count, dtype: int64

In [10]:
expected_sales = (
    df["Quantity"] * df["Unit_Price"]
).round(2)

sales_mismatch = (
    df["Total_Sales"].round(2) != expected_sales
)

print("Sales calculation mismatches:", sales_mismatch.sum())

if sales_mismatch.any():
    display(df.loc[
        sales_mismatch,
        ["Order_ID", "Quantity", "Unit_Price", "Total_Sales"]
    ].head(20))

Sales calculation mismatches: 0

In [11]:
# Find all rows with repeated Order_ID values
repeated_orders = df[
    df["Order_ID"].duplicated(keep=False)
].sort_values("Order_ID")

display(repeated_orders)

# Check whether repeated IDs have different products or details
summary = (
    repeated_orders.groupby("Order_ID")
    .agg(
        Rows=("Order_ID", "size"),
        Customers=("Customer_ID", "nunique"),
        Dates=("Order_Date", "nunique"),
        Products=("Product", "nunique"),
        Total_Sales=("Total_Sales", "sum")
    )
)

display(summary)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales
48,ORD100050,2025-10-03,CUST5523,Customer_432,NaN,Male,Pune,Chair,Furniture,9,30834.87,277513.83
118,ORD100050,2025-01-22,CUST3194,Customer_114,34.0,Male,Kolkata,Book,Education,2,25795.55,51591.10
238,ORD100050,2025-03-01,CUST8467,Customer_104,23.0,Male,Bengaluru,Book,Education,3,2860.83,8582.49
358,ORD100050,2025-02-11,CUST6467,Customer_181,24.0,Female,Pune,Rice,Grocery,7,45480.39,318362.73
478,ORD100050,2025-11-22,CUST8225,Customer_468,64.0,Male,Bengaluru,Rice,Grocery,8,38957.59,311660.72
598,ORD100050,2025-02-21,CUST8859,Customer_53,NaN,Male,NaN,Laptop,Electronics,7,20144.84,141013.88
718,ORD100050,2025-11-06,CUST7824,Customer_190,31.0,Female,Mumbai,Rice,Grocery,4,42642.59,170570.36
838,ORD100050,2025-08-03,CUST5585,Customer_289,35.0,Male,Kolkata,Chair,Furniture,9,28747.47,258727.23
958,ORD100050,2025-02-09,CUST7188,Customer_89,62.0,Male,Bengaluru,Mobile,Electronics,1,34619.77,34619.77

           Rows  Customers  Dates  Products  Total_Sales
Order_ID
ORD100050     9          9      9         5   1572642.11

In [12]:
clean_df = df.copy()

print("Original shape:", df.shape)
print("Working copy shape:", clean_df.shape)

Original shape: (1000, 12)
Working copy shape: (1000, 12)

In [13]:
clean_df["Order_Date"] = pd.to_datetime(
    clean_df["Order_Date"],
    errors="coerce"
)

print("New date type:", clean_df["Order_Date"].dtype)
print("Invalid dates:", clean_df["Order_Date"].isna().sum())

New date type: datetime64[ns]
Invalid dates: 0

In [14]:
# Record the original missing counts
print("Missing Age before:", clean_df["Age"].isna().sum())
print("Missing City before:", clean_df["City"].isna().sum())

# Fill missing ages with the median
age_median = clean_df["Age"].median()
clean_df["Age"] = clean_df["Age"].fillna(age_median)

# Preserve missing city information explicitly
clean_df["City"] = clean_df["City"].fillna("Unknown")

print("\nMissing values after treatment:")
display(clean_df.isnull().sum().to_frame("Missing_Count"))

Missing Age before: 20
Missing City before: 13

Missing values after treatment:

               Missing_Count
Order_ID                   0
Order_Date                 0
Customer_ID                0
Customer_Name              0
Age                        0
Gender                     0
City                       0
Product                    0
Category                   0
Quantity                   0
Unit_Price                 0
Total_Sales                0

In [15]:
# Check invalid ages
invalid_ages = clean_df[
    (clean_df["Age"] < 0) |
    (clean_df["Age"] > 120)
]

# Check invalid quantities and prices
invalid_quantity = clean_df[clean_df["Quantity"] <= 0]
invalid_price = clean_df[clean_df["Unit_Price"] <= 0]

print("Invalid ages:", len(invalid_ages))
print("Non-positive quantities:", len(invalid_quantity))
print("Non-positive prices:", len(invalid_price))

Invalid ages: 0
Non-positive quantities: 0
Non-positive prices: 0

In [16]:
text_columns = [
    "Order_ID",
    "Customer_ID",
    "Customer_Name",
    "Gender",
    "City",
    "Product",
    "Category"
]

for col in text_columns:
    clean_df[col] = clean_df[col].astype("string").str.strip()

print("Text fields standardized.")

Text fields standardized.

In [17]:
expected_sales = (
    clean_df["Quantity"] * clean_df["Unit_Price"]
).round(2)

sales_mismatch = (
    clean_df["Total_Sales"].round(2) != expected_sales
)

print("Sales calculation mismatches:", sales_mismatch.sum())

Sales calculation mismatches: 0

In [18]:
# Extract month and year from the date
clean_df["Sales_Month"] = clean_df["Order_Date"].dt.month_name()
clean_df["Sales_Year"] = clean_df["Order_Date"].dt.year

# Group customers by age
clean_df["Customer_Age_Group"] = pd.cut(
    clean_df["Age"],
    bins=[0, 25, 35, 50, 65, float("inf")],
    labels=["18-25", "26-35", "36-50", "51-65", "66+"]
)

display(clean_df.head())
print("Updated shape:", clean_df.shape)

,Order_ID,Order_Date,Customer_ID,Customer_Name,Age,Gender,City,Product,Category,Quantity,Unit_Price,Total_Sales,Sales_Month,Sales_Year,Customer_Age_Group
0,ORD100002,2025-02-25,CUST5529,Customer_227,30.0,Female,Bengaluru,Rice,Grocery,7,2829.77,19808.39,February,2025,26-35
1,ORD100003,2025-10-14,CUST3127,Customer_182,63.0,Male,Bengaluru,Book,Education,5,27906.16,139530.80,October,2025,51-65
2,ORD100004,2025-05-13,CUST8887,Customer_487,62.0,Female,Bengaluru,Book,Education,8,37491.06,299928.48,May,2025,51-65
3,ORD100005,2025-12-02,CUST2515,Customer_470,65.0,Female,Kolkata,Mobile,Electronics,9,28541.36,256872.24,December,2025,51-65
4,ORD100006,2025-11-20,CUST4796,Customer_380,44.0,Male,Bengaluru,Rice,Grocery,10,14036.59,140365.90,November,2025,36-50

Updated shape: (1000, 15)

In [20]:
from pathlib import Path

output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

clean_df.to_csv(
    output_dir / "cleaned_sales_dataset.csv",
    index=False
)

clean_df.to_excel(
    output_dir / "cleaned_sales_dataset.xlsx",
    index=False
)

print("Cleaned files saved to:", output_dir.resolve())

Cleaned files saved to: C:\Users\Kavya m\OneDrive\Desktop\data-immersion-wrangling\output

In [21]:
# Preserve the original IDs for reference
clean_df["Original_Order_ID"] = clean_df["Order_ID"]

# Count each occurrence of an Order_ID
occurrence = clean_df.groupby("Order_ID").cumcount()

# Keep the first ID; assign a unique suffix to later occurrences
duplicate_mask = occurrence > 0

clean_df.loc[duplicate_mask, "Order_ID"] = (
    clean_df.loc[duplicate_mask, "Original_Order_ID"]
    + "_FIX"
    + occurrence[duplicate_mask].astype(str).str.zfill(2)
)

# Validate the correction
print("Rows:", len(clean_df))
print("Unique Order IDs:", clean_df["Order_ID"].nunique())
print("Remaining duplicate Order IDs:", clean_df["Order_ID"].duplicated().sum())

display(
    clean_df[clean_df["Original_Order_ID"].duplicated(keep=False)]
    [["Original_Order_ID", "Order_ID", "Order_Date", "Customer_ID", "Product"]]
    .sort_values("Original_Order_ID")
)

Rows: 1000
Unique Order IDs: 1000
Remaining duplicate Order IDs: 0

    Original_Order_ID         Order_ID Order_Date Customer_ID Product
48          ORD100050        ORD100050 2025-10-03    CUST5523   Chair
118         ORD100050  ORD100050_FIX01 2025-01-22    CUST3194    Book
238         ORD100050  ORD100050_FIX02 2025-03-01    CUST8467    Book
358         ORD100050  ORD100050_FIX03 2025-02-11    CUST6467    Rice
478         ORD100050  ORD100050_FIX04 2025-11-22    CUST8225    Rice
598         ORD100050  ORD100050_FIX05 2025-02-21    CUST8859  Laptop
718         ORD100050  ORD100050_FIX06 2025-11-06    CUST7824    Rice
838         ORD100050  ORD100050_FIX07 2025-08-03    CUST5585   Chair
958         ORD100050  ORD100050_FIX08 2025-02-09    CUST7188  Mobile

In [22]:
from pathlib import Path

output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

clean_df.to_csv(
    output_dir / "cleaned_sales_dataset.csv",
    index=False
)

clean_df.to_excel(
    output_dir / "cleaned_sales_dataset.xlsx",
    index=False
)

print("Updated files saved successfully.")

Updated files saved successfully.

In [23]:
print("Dataset shape:", clean_df.shape)
print("Missing values:", clean_df.isnull().sum().sum())
print("Exact duplicate rows:", clean_df.duplicated().sum())
print("Duplicate Order IDs:", clean_df["Order_ID"].duplicated().sum())

sales_check = (
    clean_df["Total_Sales"]
    - clean_df["Quantity"] * clean_df["Unit_Price"]
).abs()

print("Sales calculation mismatches:", (sales_check > 0.01).sum())
print("Order_Date data type:", clean_df["Order_Date"].dtype)

Dataset shape: (1000, 16)
Missing values: 0
Exact duplicate rows: 0
Duplicate Order IDs: 0
Sales calculation mismatches: 0
Order_Date data type: datetime64[ns]

In [24]:
import pandas as pd
from pathlib import Path

output_dir = Path("output")
output_dir.mkdir(exist_ok=True)

report = pd.DataFrame([
    {
        "Issue": "Missing Age values",
        "Initial_Finding": "20 missing values",
        "Action_Taken": "Filled with median age",
        "Status": "Handled"
    },
    {
        "Issue": "Missing City values",
        "Initial_Finding": "13 missing values",
        "Action_Taken": "Replaced with Unknown",
        "Status": "Handled"
    },
    {
        "Issue": "Repeated Order_ID values",
        "Initial_Finding": "8 extra occurrences",
        "Action_Taken": "Assigned unique IDs and preserved Original_Order_ID",
        "Status": "Handled with documented assumption"
    },
    {
        "Issue": "Exact duplicate rows",
        "Initial_Finding": "0",
        "Action_Taken": "No action required",
        "Status": "Passed"
    },
    {
        "Issue": "Sales calculation mismatches",
        "Initial_Finding": "0",
        "Action_Taken": "Validated Total_Sales = Quantity * Unit_Price",
        "Status": "Passed"
    },
    {
        "Issue": "Order_Date format",
        "Initial_Finding": "Stored as object/text",
        "Action_Taken": "Converted to datetime",
        "Status": "Handled"
    }
])

report.to_csv(output_dir / "data_quality_report.csv", index=False)

display(report)
print("Data quality report saved.")

,Issue,Initial_Finding,Action_Taken,Status
0,Missing Age values,20 missing values,Filled with median age,Handled
1,Missing City values,13 missing values,Replaced with Unknown,Handled
2,Repeated Order_ID values,8 extra occurrences,Assigned unique IDs and preserved Original_Ord...,Handled with documented assumption
3,Exact duplicate rows,0,No action required,Passed
4,Sales calculation mismatches,0,Validated Total_Sales = Quantity * Unit_Price,Passed
5,Order_Date format,Stored as object/text,Converted to datetime,Handled

Data quality report saved.